name: Test Codebase

on:
  pull_request:
    branches: [ master, dev ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ feature/tests ]
permissions:
  contents: read

jobs:
  start:
    name: Start State ðŸš€ðŸš€ðŸš€
    runs-on: windows-latest
    steps:
    - name: Starting
      id: init
      run: |
        echo "Starting linting of ${{ github.repository }}"

  run_all_tests:
    name: Run all Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    needs: start
    steps:
      - name: Checkout for ${{ runner.os }}
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
      - name: Run unit/integration tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        if: ${{ runner.os == 'macOS' }}
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build app
        run: npm run build
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run playwright
        if: matrix.os == 'ubuntu-latest'
      - run: npm run playwright
        if: matrix.os != 'ubuntu-latest'

  end:
    name: End State âœ…âœ…âœ…
    runs-on: windows-latest
    needs: run_all_tests
    steps:
    - name: Ending
      id: init
      run: |
        echo "Ending linting of ${{ github.repository }}"